#spring:
#  application:
#    name: aws-image-app
#
#  thymeleaf:
#    cache: false  # Disable cache during development
#    prefix: classpath:/templates/
#    suffix: .html
#
#
#  datasource:
#    url: jdbc:postgresql://s3-with-rds-app-multiazpostgresqldatabase-vnxplxkoyh40.cxo2ykisqxby.us-east-2.rds.amazonaws.com/imagemetadatadb #${DB_URL}
#    username: dbadmin  #${DB_USERNAME}
#    password: Oppong0243911336 #${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 600000
#      max-lifetime: 1800000
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#server:
#  port: 3004
#  shutdown: graceful
#
#aws:
#  region: us-east-1 # ${AWS_REGION}
#  s3:
#    bucket-name: week5-lab-bucket-nicholas # ${S3_BUCKET_NAME}
#    presigned-url-expiration: 3600 # in seconds
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  endpoint:
#    health:
#      show-details: always
#
#logging:
#  level:
#    root: INFO
#    com.awsimageapp: DEBUG
#    org.hibernate.SQL: INFO

spring:
  application:
    name: aws-image-app
  datasource:
    # URL will be dynamically constructed in DataSourceConfig
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  hikari:
    maximum-pool-size: 10
    connection-timeout: 30000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 3004
  shutdown: graceful

aws:
  region: ${AWS_REGION:us-east-1}
  ssm:
    db-endpoint-param: /s3-image-upload-app/database/endpoint
    db-name-param: /s3-image-upload-app/database/name
    db-username-param: /s3-image-upload-app/database/username
    db-password-param: /s3-image-upload-app/database/password
    s3-bucket-param: /s3-image-upload-app/s3/bucket-name

  s3:
    bucket: ${aws.ssm.s3-bucket-param}
    presigned-url-expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.awsimageapp: DEBUG
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: DEBUG


